const testReviews = [
	'The Shawshank Redemption | Absolutely loved it! The storyline was captivating from start to finish.',
	'Breaking Bad | The acting was phenomenal. Each character was so well portrayed.',
	'Avatar | Visually stunning! The cinematography was top-notch.',
	'Friends | A perfect blend of humor and drama. Highly recommend!',
	"Game of Thrones | One of the best series I've seen in a long time. Can't wait for the next season!",
	'Inception | The plot twists kept me on the edge of my seat. Brilliantly done!',
	'The Lion King | Amazing soundtrack that perfectly complemented the scenes.',
	'Stranger Things | Great character development throughout the series.',
	'Black Mirror | Engaging and thought-provoking. A must-watch.',
	'The Godfather | The director did an excellent job. Every episode was a masterpiece.',
	'Twilight | The plot was predictable and unoriginal.',
	'Cats | Poor acting. The characters felt very flat and unconvincing.',
	'Sharknado | The special effects were subpar and looked cheap.',
	"The Room | I found it boring and slow-paced. Couldn't finish it.",
	'Lost | The storyline was all over the place and hard to follow.',
	'Dexter | Disappointing ending. It felt rushed and incomplete.',
	'Fifty Shades of Grey | Too many clichés and overused tropes.',
	'The Meg | The dialogue was cringeworthy and unnatural.',
	'Bird Box | Not worth the hype. I expected much more.',
	'Gigli | The characters were unlikeable and poorly written.',
	"Grey's Anatomy | It was okay. Nothing extraordinary, but not terrible either.",
	'The Walking Dead | Some episodes were great, others not so much.',
	"The Matrix | The movie had its moments, but it wasn't consistently good.",
	'Suits | Decent watch if you have time to kill, but not a must-see.',
	'Supernatural | Mixed feelings. Some parts were enjoyable, others were not.',
	'Westworld | The plot was interesting, but it could have been executed better.',
	'How I Met Your Mother | The performances were hit or miss. Some actors stood out more than others.',
	'Pirates of the Caribbean | Average movie. It had some good scenes, but overall it was forgettable.',
	"The Witcher | It had potential, but it didn't quite live up to it.",
	'The Office | Neither great nor awful. It was a typical, run-of-the-mill show.',
];

export default testReviews;
